PREMA = 60.0
NOTA_MINIMA = 1.0
NOTA_APROBACION = 4.0
NOTA_MAXIMA = 7.0
PUNTAJE_MINIMO = 0
PUNTAJE_MAXIMO = 67
PUNTAJE_APROBACION = (PREMA * PUNTAJE_MAXIMO) / 100

for PUNTAJE_ALUMNO in range(PUNTAJE_MINIMO, PUNTAJE_MAXIMO + 1):

	if PUNTAJE_ALUMNO <= PUNTAJE_APROBACION:
		NOTA_ALUMNO = (((NOTA_APROBACION - NOTA_MINIMA) / (PUNTAJE_APROBACION - PUNTAJE_MINIMO)) * (PUNTAJE_ALUMNO - PUNTAJE_MINIMO)) + NOTA_MINIMA

	elif PUNTAJE_ALUMNO > PUNTAJE_APROBACION:
		NOTA_ALUMNO = (((NOTA_MAXIMA - NOTA_APROBACION) / (PUNTAJE_MAXIMO - PUNTAJE_APROBACION)) * (PUNTAJE_ALUMNO - PUNTAJE_APROBACION)) + NOTA_APROBACION

	print("PUNTOS: {} -> NOTA: {}".format(PUNTAJE_ALUMNO, round(NOTA_ALUMNO,1)))